tap "codeclimate/formulae"
tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/services"
tap "caskroom/fonts"
tap "caskroom/versions"
tap "caskroom/cask"
brew "ack"
brew "coreutils"
brew "ctags"
brew "dark-mode"
brew "node"
brew "heroku"
brew "htop"
brew "python"
brew "httpie"
brew "hub"
brew "imagemagick", args: ["with-webp"]
brew "jq"
brew "mas"
brew "mysql"
brew "postgresql", restart_service: true
brew "python@2"
brew "ruby"
brew "tmux"
brew "tree"
brew "wget"
brew "zsh-syntax-highlighting"
cask "amazon-music"
cask "boom-3d"
cask "cyberduck"
cask "dbeaver-community"
cask "docker"
cask "dropbox"
cask "firefox"
cask "grammarly"
cask "insomnia"
cask "iterm2"
cask "java"
cask "kap"
cask "kindle"
cask "ngrok"
cask "numi"
cask "opera"
cask "opera-neon"
cask "rescuetime"
cask "skype"
cask "slack"
cask "sonic-pi"
cask "spectacle"
cask "tipp10"
cask "vlc"
cask "caskroom/fonts/font-source-code-pro"
cask "caskroom/versions/firefox-developer-edition"
cask "caskroom/versions/google-chrome-canary"
mas "Bandwidth+", id: 490461369
mas "CleanMyDrive 2", id: 523620159
mas "Freckle", id: 879917538
mas "Install macOS High Sierra", id: 0
mas "Install macOS High Sierra", id: 0
mas "LastPass", id: 926036361
mas "Taurine", id: 960276676
mas "Xcode", id: 497799835
