tap "buo/cask-upgrade"
tap "codeclimate/formulae"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "ack"
brew "openssl"
brew "python"
brew "awscli"
brew "cmatrix"
brew "coreutils"
brew "ctags"
brew "dark-mode"
brew "gawk"
brew "htop"
brew "httpie"
brew "hub"
brew "imagemagick", args: ["with-webp"]
brew "jq"
brew "mas"
brew "mysql"
brew "node"
brew "pipenv"
brew "postgresql", restart_service: true
brew "python@2"
brew "ruby"
brew "tmux"
brew "tree"
brew "wget"
brew "zsh"
brew "zsh-syntax-highlighting"
brew "heroku/brew/heroku"
cask "amazon-music"
cask "android-file-transfer"
cask "android-platform-tools"
cask "android-sdk"
cask "android-studio"
cask "boom-3d"
cask "cyberduck"
cask "dbeaver-community"
cask "docker"
cask "dropbox"
cask "firefox"
cask "firefox-developer-edition"
cask "font-source-code-pro"
cask "google-chrome"
cask "google-chrome-canary"
cask "grammarly"
cask "insomnia"
cask "iterm2"
cask "java"
cask "kap"
cask "kindle"
cask "ngrok"
cask "numi"
cask "opera"
cask "opera-neon"
cask "pgadmin4"
cask "pomodone"
cask "rescuetime"
cask "skype"
cask "slack"
cask "sonic-pi"
cask "spectacle"
cask "telegram"
cask "tipp10"
cask "visual-studio-code-insiders"
cask "vlc"
mas "Bandwidth+", id: 490461369
mas "Freckle", id: 879917538
mas "LastPass", id: 926036361
mas "Notebook", id: 1173152781
mas "Taurine", id: 960276676
mas "Trello", id: 1278508951
mas "Xcode", id: 497799835
