duti -s com.vscodium public.json all
duti -s com.vscodium public.plain-text all
duti -s com.vscodium public.python-script all
duti -s com.vscodium public.shell-script all
duti -s com.vscodium public.source-code all
duti -s com.vscodium public.text all
duti -s com.vscodium public.unix-executable all
# this works for files without a filename extension
duti -s com.vscodium public.data all

duti -s com.vscodium .c all
duti -s com.vscodium .cpp all
duti -s com.vscodium .cs all
duti -s com.vscodium .css all
duti -s com.vscodium .go all
duti -s com.vscodium .java all
duti -s com.vscodium .js all
duti -s com.vscodium .sass all
duti -s com.vscodium .scss all
duti -s com.vscodium .less all
duti -s com.vscodium .vue all
duti -s com.vscodium .cfg all
duti -s com.vscodium .json all
duti -s com.vscodium .jsx all
duti -s com.vscodium .log all
duti -s com.vscodium .lua all
duti -s com.vscodium .md all
duti -s com.vscodium .php all
duti -s com.vscodium .pl all
duti -s com.vscodium .py all
duti -s com.vscodium .rb all
duti -s com.vscodium .ts all
duti -s com.vscodium .tsx all
duti -s com.vscodium .txt all
duti -s com.vscodium .conf all
duti -s com.vscodium .yaml all
duti -s com.vscodium .yml all
duti -s com.vscodium .toml all
