duti -s dev.zed.Zed public.json all
duti -s dev.zed.Zed public.plain-text all
duti -s dev.zed.Zed public.python-script all
duti -s dev.zed.Zed public.shell-script all
duti -s dev.zed.Zed public.source-code all
duti -s dev.zed.Zed public.text all
duti -s dev.zed.Zed public.unix-executable all
# this works for files without a filename extension
duti -s dev.zed.Zed public.data all

duti -s dev.zed.Zed .c all
duti -s dev.zed.Zed .cpp all
duti -s dev.zed.Zed .cs all
duti -s dev.zed.Zed .css all
duti -s dev.zed.Zed .go all
duti -s dev.zed.Zed .java all
duti -s dev.zed.Zed .js all
duti -s dev.zed.Zed .sass all
duti -s dev.zed.Zed .scss all
duti -s dev.zed.Zed .less all
duti -s dev.zed.Zed .vue all
duti -s dev.zed.Zed .cfg all
duti -s dev.zed.Zed .json all
duti -s dev.zed.Zed .jsx all
duti -s dev.zed.Zed .log all
duti -s dev.zed.Zed .lua all
duti -s dev.zed.Zed .md all
duti -s dev.zed.Zed .php all
duti -s dev.zed.Zed .pl all
duti -s dev.zed.Zed .py all
duti -s dev.zed.Zed .rb all
duti -s dev.zed.Zed .ts all
duti -s dev.zed.Zed .tsx all
duti -s dev.zed.Zed .txt all
duti -s dev.zed.Zed .conf all
duti -s dev.zed.Zed .yaml all
duti -s dev.zed.Zed .yml all
duti -s dev.zed.Zed .toml all
